# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode6.4
cache: cocoapods

notifications:
  email:
    recipients:
      - dmyt.ov@gmail.com
    on_success: change
    on_failure: change

podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
#- set -o pipefail && xcodebuild test -workspace Example/DOCheckboxControl.xcworkspace -scheme DOCheckboxControl-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c #No tests for now...
- set -o pipefail && xcodebuild -workspace Example/DOCheckboxControl.xcworkspace -scheme DOCheckboxControl-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
